### PR TITLE
Switch to ReactOS Lunar theme

### LINKED ISSUE #10: Modern theme is subtly broken
Examples:

* The color picker in photoscape is too small
  image
* Sliders don't have any background and/or markings
  modern-graphics

### PR DESCRIPTION
**Pull request by merlijn-sebrechts**
The current default theme (ReactOS Modern) is subtly broken: https://github.com/snapcrafters/sommelier-core/issues/10

This switches the theme to ReactOS Lunar, which is a lot more polished.

* Before:  
  modern-graphics
  image

  
* After: (slider now has background)
  lunar-graphics
  image

fixes: https://github.com/snapcrafters/sommelier-core/issues/10

## Note to reviewers

This repository contains the source for a part used by a bunch of different snaps. Examples:

* notepad-plus-plus: https://github.com/mmtrt/notepad-plus-plus
* Photoscape: https://github.com/snapcrafters/photoscape/

You can test it by cloning the repo of one of those snaps and changing `source-branch: "1.0"` to `source-branch: "pull/11/head"` in the `sommelier` part. Rebuild the snap and install it locally. You can see dialog of the first screenshot by running `<snap-name>.wine winecfg`.

### CODE REVIEW

**Comment by merlijn-sebrechts** [comment]
Also pinging @mmtrt and @diddledan since they have some experience with this part.

**Review by lucyllewy — DISMISSED** [review]
I'd like for the theme to be switched on already installed apps, too, if it fixes a bug. At the moment in this PR it will only affect newly-installed apps - if the prefix is already created then it'll not receive this fix.

**Comment by merlijn-sebrechts** [comment]
@diddledan 

I agree already installed apps should have this fix too. I think this is already the case with the current code. The theme is set in `init_wine` which runs every time the revision of the snap changes.

https://github.com/snapcrafters/sommelier-core/blob/47845386fbeefc0f4a7e4ed71d45b9a1bc091b26/scripts/sommelier#L374-L376

So the first snap built with the new sommelier-core should automatically upgrade the theme. Is this not the case?

**Comment by mmtrt** [comment]
overall its good theme but has issue that it doesn't renders round selection mark also volume rocker has low hightlight color in bottom as compare to modern theme and seek bar is fixed but bottom color is low highlight

with modern theme

sshot-1-md

with lunar theme

sshot-2-ln

**Comment by lucyllewy** [comment]
> So the first snap built with the new sommelier-core should automatically upgrade the theme. Is this not the case?

Aah I see it now. I misread the flow through the script. Ignore my previous comment then 😃

**Review by lucyllewy — APPROVED** [review]

**Comment by merlijn-sebrechts** [comment]
@mmtrt selection marks are present on my system. Though the volume slider and some contrast is problematic.

image

I even tried to install your foobar2000 snap from `edge` channel and I still see the selection marks.

I'd rather have a theme that's "perfect". My second option was to use the LunaVX theme. I was not able to find any bugs with the LunaVX theme.

* Download theme: https://web.archive.org/web/20070311001601/http://archive.geeknewz.com/download/LunaVX.zip
* Thread about the theme: https://web.archive.org/web/20070611190149/http://www.geeknewz.com/board/index.php?act=ST&f=20&t=1293

It renders everything correctly, including the volume slider:

image

The main issue is that it's "freeware" without a real license.

I've searched for open source themes but, apart from ReactOS, I can't find many. Modern and Lunar seem to be the least broken ReactOS themes. Do you have any suggestions for an open source theme or do you think it's fine just to use LunaVX?

**Comment by merlijn-sebrechts** [comment]
Closing this PR since it introduces regressions

**Comment by mmtrt** [comment]
New wine theme soon we should use it still thats wip but still doesn't have license though.

https://www.winehq.org/pipermail/wine-devel/2021-June/188444.html

**Comment by merlijn-sebrechts** [comment]
@mmtrt Good find! The source of that theme is published here using the LGPL license: https://github.com/zzhiyi/wine/tree/dev/themes/light

I'll create a new PR with this theme.

**Comment by mmtrt** [comment]
@galgalesh nice lets see how it works 🤞

**Pull request closed without merging**
