### PR TITLE
Change theme to 'Light' because 'Modern' has bugs

### LINKED ISSUE #10: Modern theme is subtly broken
Examples:

* The color picker in photoscape is too small
  image
* Sliders don't have any background and/or markings
  modern-graphics

### PR DESCRIPTION
**Pull request by merlijn-sebrechts**
The current default theme (ReactOS Modern) is subtly broken: https://github.com/snapcrafters/sommelier-core/issues/10

This switches the theme to the Light theme by Wine developer Zhiyi Zhang, which is a lot more polished.

* Before:  
  modern-graphics

  
* After: (slider now has background)
  image

fixes: https://github.com/snapcrafters/sommelier-core/issues/10

## Note to reviewers

This repository contains the source for a part used by a bunch of different snaps. Examples:

* notepad-plus-plus: https://github.com/mmtrt/notepad-plus-plus
* Photoscape: https://github.com/snapcrafters/photoscape/

You can test it by cloning the repo of one of those snaps and changing the `sommelier` part to this:

```yaml
  sommelier:
    plugin: make
    source: https://github.com/galgalesh/sommelier-core.git
    source-branch: wine-light-theme
```

Rebuild the snap and install it locally. You can see dialog of the first screenshot by running `<snap-name>.wine winecfg`.

*Note: This is the second try for a new theme. [The first try](https://github.com/snapcrafters/sommelier-core/pull/11) had a few regressions.*

### CODE REVIEW

**Comment by merlijn-sebrechts** [comment]
@mmtrt the volume slider in foobar2000 is slightly better

image

**Comment by merlijn-sebrechts** [comment]
* @mmtrt Can you review this too to make sure everything is rendered correctly with this new theme?
* @diddledan for context; we decided not to go through with the previous theme change because it introduced some additional bugs. This theme _should_ be perfect.

**Comment by mmtrt** [comment]
@galgalesh looks and works good didn't any ground breaking issues apart from this side cut off.
test

**Review by lucyllewy — APPROVED** [review]
LGTM - I've tested with a local snap

**Comment by merlijn-sebrechts** [comment]
Great, thanks @diddledan !

**Pull request merged**
