### PR TITLE
remove prefix envar from winetricks 

### PR DESCRIPTION
**Pull request by mmtrt**
fixes installing verbs to actual wineprefix

### CODE REVIEW

**Comment by merlijn-sebrechts** [comment]
Oh, wow, I don't know how I missed that.. Thanks!

**Comment by merlijn-sebrechts** [comment]
Any idea if this breaks existing snaps? I'm not sure if a snap would depend on this weird behavior. I'm merging it into master now and I'll do some testing before I release it to 1.x.

**Comment by mmtrt** [comment]
it shouldn't, snap having env `WINEPREFIX: "$SNAP_USER_COMMON/.wine"` defined were broken.

**Comment by merlijn-sebrechts** [comment]
Ok, I also checked other github repo's and I can't find any other using sommelier-core _and_ winetricks. I released it to `1.0`.

**Pull request merged**
