### PR TITLE
update cjk font checks and configs

### PR DESCRIPTION
**Pull request by mmtrt**
adds jp kr config files and seprates hk as per noto cjk font conf and it also hopefully fixes issue with tc sc #12

### CODE REVIEW

**Comment by merlijn-sebrechts** [comment]
This looks good at first glance but is this what the edge build of npp uses? It seems Lin's problem is still present in tthat version.

**Comment by mmtrt** [comment]
@galgalesh yes it does and looks like issue is fixed in last post of Lin's with having fresh wineprefix but It still has few UI elements of font rendering as squares.

**Review by merlijn-sebrechts — CHANGES_REQUESTED** [review]
@mmtrt your latest changes don't seem to be working because the `.reg` files use `UTF-8` encoding while the hex-encoded strings in it use `UTF-16 LE`.

The easiest solution is to change the encoding of the `.reg` files to `UTF-16 LE`. The files in the sample snap you sent us were encoded correctly.

I would also add a comment to each file noting that they have to be encoded in UTF-16 LE to work. So we don't forget in the future.

**Comment by mmtrt** [comment]
@galgalesh good catch also files had break type set to `Unix (LF)` I've change it back to `windows (CR LF)`, all should be good now.

**Review by merlijn-sebrechts — APPROVED** [review]
Yes, I can confirm it works now, thanks!

**Comment by merlijn-sebrechts** [comment]
@mmtrt I squashed this into master, but now master should be merged into the 1.0 branch. Can you try to create a separate pull request from `snapcrafters:master` to `snapcrafters:1.0`? If that's possible, that would be the easiest. I could make the pull request myself, but then we need another snapcrafter to review my pull request.

**Comment by mmtrt** [comment]
I couldn't create PR from `snapcrafters:master` to `snapcrafters:1.0` so I pull theses changes to my fork `master` then created `MR` from there.

**Pull request merged**
